import '../globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Link from 'next/link';

import Footer from '../../components/footer';

import Dropdown from '../../components/dropdown';


const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Next Site',
  description: 'Generated by create next + sanity',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  return (
    <html lang="en">
      <body>

        <Dropdown />

        <main>{children}</main>

        <Footer />


      </body>

    </html>
  )
}
